<?xml version="1.0" encoding="utf-8"?>
<Database Name="InvoiceLog" Class="InvoiceDC" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=gandalf\sqlexpress;Initial Catalog=InvoiceLog;Persist Security Info=True;User ID=sa" SettingsObjectName="InvoiceLog.Properties.Settings" SettingsPropertyName="InvoiceLogConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Invoice" Member="Invoices">
    <Type Name="Invoice">
      <Column Name="InvoiceId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VendorName" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="InvoiceNumber" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PONumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Terms" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DueDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="Exported" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsCredit" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Memo" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Vendor" Member="Vendors">
    <Type Name="Vendor">
      <Column Name="VendorId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VendorName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ScanInvoices" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Terms" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="InvNumFormat" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CategoryName" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Memo" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>